Adding support for custom ports for alb_subraphs
apollographql/terraform-graphos-aws pull request #5
Opened 2023-10-10 02:34 UTC by marcussaad

### Background

👋 Hello! Recently onboarded into the dedicated experience and I tried playing with the graphos integration today. However, after battling with things for a bit, I figured out that our infrastructure needed to change considerably in order for the communication to happen on port 80 by default. That lead me to come look at the source code and see if it wouldn't be possible to pass a custom port number where the ALB expects communication.

To my surprise, the underlying module already supports a custom port, but `alb_subgraphs` does not receive that value in it's definition.

### Changes
- Tweak README to mention that `alb_subgraphs` can take a `alb_port` variable that allows one to customize the communication port.
- Added `hcl` markdown to hcl block.
- Changed README lingo around port 80 being required
- Updated `alb_subgraphs` to receive a `alb_port` argument that is passed down to `aws_vpclattice_target_group` and `aws_vpclattice_target_group_attachment`.

2023-10-10 02:34 UTC, apollo-cla commented
@marcussaad: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2023-10-11 14:26 UTC, nmoutschen requested changes
Hey @marcussaad !

Thanks a lot for the PR and for your feedback! I agree that letting users define a different port for ALBs makes a lot of sense. I just have a small change request around using `optional` to default to port 80.

2023-10-11 14:26 UTC, nmoutschen commented on variables.tf
> +    alb_port = number
Using `optional(number, 80)` to default to port 80. 

```suggestion
    alb_port = optional(number, 80)
```

2023-10-11 14:26 UTC, nmoutschen commented on README.md
> +```hcl
Thanks for the doc improvements here!

2023-10-11 14:28 UTC, nmoutschen approved these changes

2023-10-11 14:28 UTC, merged

2023-10-11 15:41 UTC, marcussaad commented
@nmoutschen thanks for taking it over 👍